apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 'ghcr.io/vi2hnu/chat-website-backend:latest'
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: backend-secrets
          env:
            - name: REDIS_URL
              value: redis://redis-service:6379